### ISSUE TITLE
Change of ascii is not working.

### ISSUE THREAD

**Issue by niksingh710** [adriankarlen/textfox#113]
```nix
      newtabLogo = '' __ _           __\A / _(_)_ __ ___ / _| _____  __\A | |_| | '__/ _ \ |_ / _ \ \/ /\A |  _| | | |  __/  _| (_) >  <\A |_| |_|_|  \___|_|  \___/_/\_\ '';
```

above is the snippet added in my home-manager config.

it should be 
```sh
  __ _           __           
 / _(_)_ __ ___ / _| _____  __
| |_| | '__/ _ \ |_ / _ \ \/ /
|  _| | | |  __/  _| (_) >  < 
|_| |_|_|  \___|_|  \___/_/\_\
                              
```

i have seen the given example so added `\A` in the string still on the tab `textfox` is showing.

**Comment by adriankarlen** [comment]
Hi, this seems to be an nix issue (I don't use nix) so it is quite hard for me to debug, but replacing changing the ascii inside `config.css` seems to work just fine with the string you provided (removing the '', which I assume is some nix thing).

This is the code for the option: https://github.com/adriankarlen/textfox/blob/e0d002eea7a5a3791bbf3f4b64c9197a531a4f96/nix/modules/options.nix#L33-L44

Am I understanding Nix correctly when I say that nix should fix the newline stuff by it self?

**Comment by niksingh710** [comment]
I have just tried this, home-manager is placing the correct content in config.css.

i also tried removing config.css and paste the default one with the changed string still the new tab page is showing `textfox` ascii not the `firefox` one.

the readme mentions make the string `""` blank to remove the ascii art; still getting it.

**Comment by snaeil** [comment]
I can confirm this problem using nix home-manger on non-nixos linux.
Changing the value of `--tf-newtab-logo` both in `defaults.css` and `config.css` didn't change anything for me.

> Am I understanding Nix correctly when I say that nix should fix the newline stuff by it self?

I also understand this as you @adriankarlen .
Since this was intoduced with https://github.com/adriankarlen/textfox/pull/104 so @nyukuru might be able to provide more information?

**Comment by nyukuru** [comment]
> Am I understanding Nix correctly when I say that nix should fix the newline stuff by it self?

This is correct, the nix option will replace literal newlines with "\A" literally, also converting "\" to "\\" literally.

My suspicion is that home-manager is setting the css variable in a way that breaks the syntax which makes it not get set (exactly how is not clear to me). Could either @snaeil or @niksingh710 share their generated config.css?

**Comment by snaeil** [comment]
In my hm configuration I use textfox like this:
```nix
  textfox = {
    enable = true;
    profile = "convenient";
    config = {
      background = {
        color = "#191724";
      };
      border = {
        color = "#908caa";
        width = "1px";
        transition = "1.0s ease";
        radius = "1px";
      };
      tabs.horizontal.enable = true;
      displayNavButtons = true;
      displayWindowControls = true;
      displayTitles = true;
      displayUrlbarIcons = true;
      displaySidebarTools = true;
      newtabLogo = ''
                Hello world!
                What's going on?
      '';
      font = { 
        size = "12px";
        accent = "#c4a7e7";
      };
    };

  };
```

The resulting `config.css`:

```css
:root {
  --tf-font-family: "SF Mono", Consolas, monospace;
  --tf-font-size: 12px;
  --tf-accent: #c4a7e7;
  --tf-bg: #191724;
  --tf-border: #908caa;
  --tf-border-transition: 1.0s ease;
  --tf-border-width: 1px;
  --tf-rounding: 1px;
  --tf-margin: 0.8rem;
  --tf-display-horizontal-tabs: block;
  --tf-display-window-controls: flex;
  --tf-display-nav-buttons: flex;
  --tf-display-urlbar-icons: flex;
  --tf-display-sidebar-tools: flex;
  --tf-display-titles: flex;
  --tf-newtab-logo: "Hello world!\AWhat's going on?\A";
}
```

How it looks

![Image](https://github.com/user-attachments/assets/b8a0b10e-dc9c-4a2b-ab41-c6e773d351fb)

**Comment by niksingh710** [comment]
`config.css`:
```css
:root {
  --tf-font-family: JetBrainsMono Nerd Font;
  --tf-font-size: 14px;
  --tf-accent: #ebdbb2;
  --tf-bg: #202020;
  --tf-border: #ebdbb2;
  --tf-border-transition: 0.2s ease;
  --tf-border-width: 1px;
  --tf-rounding: 0px;
  --tf-margin: 0.8rem;
  --tf-display-horizontal-tabs: none;
  --tf-display-window-controls: none;
  --tf-display-nav-buttons: flex;
  --tf-display-urlbar-icons: none;
  --tf-display-sidebar-tools: flex;
  --tf-display-titles: none;
  --tf-newtab-logo: "  __ _           __\A / _(_)_ __ ___ / _| _____  __\A| |_| | '__/ _ \\ |_ / _ \\ \\/ /\A|  _| | | |  __/  _| (_) >  <\A|_| |_|_|  \\___|_|  \\___/_/\\_\\\A\A";
}
```

`home-manager`:
```nix
  textfox = with colors;{
    enable = config.ndots.browser.firefox.textfox;
    profile = "default";
    config = {
      # Optional config
      background.color = "#${base00}";
      border = {
        color = "#${base06}";
        width = "1px";
        radius = if opts.rounding then "10px" else "0px";
      };
      displayWindowControls = false;
      displayNavButtons = true;
      displayTitles = false;
      newtabLogo = # text
        ''
            __ _           __
           / _(_)_ __ ___ / _| _____  __
          | |_| | '__/ _ \ |_ / _ \ \/ /
          |  _| | | |  __/  _| (_) >  <
          |_| |_|_|  \___|_|  \___/_/\_\

        '';
      font = {
        family = config.stylix.fonts.monospace.name;
        accent = "#${base06}";
      };
    };
  };

```
