### ISSUE TITLE
Spacing between tabs and main boxes are inconsistent/weird now

### ISSUE THREAD

**Issue by Alan-J-Bibins** [adriankarlen/textfox#115]
I am not sure if this was intended or but

![Image](https://github.com/user-attachments/assets/65b9a436-2d66-4c18-99d9-913fb56cb695)

after a system update, the gap between the tab and main content boxes have increased, not just that but the "main" label of the main box has been shifted a few pixels up like so:

![Image](https://github.com/user-attachments/assets/bc9c0615-153c-4834-9c35-f62e209edd0c)

Firefox version is 135.0.1

Here is my config.css:
```css
:root {
    --tf-nav-buttons-display: block;
}

#sidebar-box {
    width: fit-content !important;
    max-width: 180px !important;
    height: var(--sidebar-height);
    padding: 0 0px;
}

#back-button,
#forward-button,
#star-button-box,
.urlbar-page-action {
    display: block;
}


```

**Comment by adriankarlen** [comment]
I am using the same firefox version as you and am unable to reproduce this issue with your provided `config.css` are you sure that you using an up to date version of textfox?

**Comment by Alan-J-Bibins** [comment]
So to test again I cloned the textfox repository, made a new user profile in firefox and ran the tf-install.sh with the root directory of the new user profile, the screenshot attached below is what I see, no clue as to what is going wrong.

![Image](https://github.com/user-attachments/assets/a9c52f21-0d76-4aad-a40f-03befcc51811)

![Image](https://github.com/user-attachments/assets/d770ddde-e38a-41a0-b601-6d8648ae3dd4)

**Comment by adriankarlen** [comment]
Hmm, weird. Guess it could have something to do with os, or perhaps resolution. Is the misalignment consistent on different resolutions on your screen?

**Comment by Alan-J-Bibins** [comment]
![Image](https://github.com/user-attachments/assets/a53e68b8-147f-40da-a26d-2c7c92a84d6a)

Checked out commit 69c235b0 

The 'main' text is not displaced in this version, yet the colors are not the same as they should be, the gap's colors should be the same as that of the bg of the navbar and sidebar.

I think it might be a combination of some changes in textfox along with changes present in the recent firefox update, I have yet to try an older version of firefox. Will figure out which commit caused the issue of the "main" text displacement.

**Comment by Alan-J-Bibins** [comment]
Ok here is firefox 134.0.2 in a fresh user profile along with textfox and sidebery
![Image](https://github.com/user-attachments/assets/70f98c58-7dc8-47f2-b870-3ac4110b1cef)


With firefox 135.0.1 (the latest)
![Image](https://github.com/user-attachments/assets/0d2b8138-8b25-4ebf-a8b1-6ff8a8f4bf28)

Both versions are using the older version of textfox, ie commit 69c235b

The change in color of the gaps seems to have been part of a firefox update

**Comment by Alan-J-Bibins** [comment]
#### Fix for the "main" label being displaced:
This is what I added in my config.css:

```css
#tabbrowser-tabbox {
  &::before {
    transform: translateY(8px);
  }
}

```

It seems that with some new firefox update, the "main" text got displaced so just translating it downwards brings it back to its intended position.

The colors for the gap are still different from what is intended for textfox, aka --tf-bg, it is not getting applied after a firefox update.
