### ISSUE TITLE
Dropdown menus are not readable

### ISSUE THREAD

**Issue by HeyUKonrad** [adriankarlen/textfox#126]
I tried not using FireFox Colors but the issue remained

![Image](https://github.com/user-attachments/assets/901acc88-c9ef-409e-a24e-0a9f04e3ff12)

**Comment by bitboxer** [comment]
You can change that with something like this in the `menu.css` for example:

```css
menu,
menuitem,
menucaption {
  color: white;
}
```
