### ISSUE TITLE
"Main" window border dissapears when fullscreen

### ISSUE THREAD

**Issue by HazelTuah214** [adriankarlen/textfox#144]
Consistent issue. Border is there when out of fullscreen. I don't believe I have changed any setting pertaining to this border. 

![Image](https://github.com/user-attachments/assets/2db68b70-b47d-48e5-99e2-338d3409f078)

**Comment by adriankarlen** [comment]
The border is there before? but not after? I wonder if there is some weird overwrite happening if that's the case.

**Comment by Aetherosz** [comment]
Hey Adrian. So the border is there but when you move to fullscreen it disappears and becomes like the screenshot.

**Comment by doofenshmirtzzz** [comment]
Seems to be related to this snippet in `browser.css`:

```css
:root[inFullscreen="true"] {
  #tabbrowser-tabbox {
    margin: 0 !important;
    border: none;
    padding: 0 !important;
    transition: none;
    &::before {
      display: none;
    }
  }
}
```

If commented out, the issue is resolved for me. Not sure what's the intended purpose of these rules

Edit: Commenting this out made the border appear in every fullscreen (e.g. YouTube videos). I'm not sure if this can be configured only for F11 fullscreen, though

Edit2: found `inDOMFullscreen` attribute and replacing `inFullscreen` with it seems to have disabled the border for YouTube videos, while still showing it in F11. Needs more testing though
